perks:
  Fly:
    action: toggleFly
  Nick:
    action: nick
  Chat Colour:
    action: chatColour
    type: form
    title: Change colour
    content: "Current colour: $currentColour"
    buttons:
      - Red
      - Blue
      - Rainbow
      - Remove
  Kill Message:
    action: killMessage
    type: form
    title: Kill message
    content: "Current kill message: $currentMessage"
    buttons:
      - Epic
      - Hello
  Particles:
    action: particles
    type: form
    title: Particles
    content: "Current particle: $currentParticle"
    buttons:
      - Villager Angry
      - Heart

randomNicks: []
death-format:
  Epic: "$deathPlayer was dead by $killerPlayer with $killerHealth"

deathWorldsAllowed:
  - world
flyingWorldsAllowed:
  - world